name: Deploy Node.js App to EC2 via SSM (OIDC)

on:
  push:
    branches:
      - main

permissions:
  id-token: write    # For OIDC
  contents: read     # Read repo content

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::235494815059:role/github-actionOIDC
        aws-region: eu-north-1

    - name: Deploy via SSM to EC2
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy Node App via GitHub OIDC" \
          --instance-ids "i-04ac66feee251e0c0" \
          --parameters 'commands=[
            "APP_DIR=/home/ubuntu/myapp",
            "if [ ! -d \"$APP_DIR\" ]; then git clone https://github.com/12rutuja/nodejs-ssl-server.git $APP_DIR && cd $APP_DIR && npm install; else cd $APP_DIR && git pull origin main; fi",
            "cd $APP_DIR",
            "which node && node -v",
            "which pm2 || sudo npm install -g pm2",
            "pm2 restart hello-node || pm2 start server.js --name hello-node",
            "pm2 save",
            "echo App is running from $(pwd)",
            "pm2 list"
          ]' \
          --region eu-north-1 \
          --output text
