name: Deploy Node.js App to EC2 via OIDC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::235494815059:role/github-actionOIDC
        aws-region: eu-north-1

    - name: Deploy via SSM to EC2
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy Node.js App via GitHub Actions" \
          --instance-ids "i-0exampleinstanceid" \
          --parameters 'commands=[
            "cd ~/myapp || git clone https://github.com/12rutuja/nodejs-ssl-server.git ~/myapp",
            "cd ~/myapp",
            "git pull origin main",
            "npm install",
            "pm2 start server.js --name hello-node || pm2 restart hello-node",
            "pm2 save"
          ]' \
          --region eu-north-1 \
          --output text
