name: Deploy Node.js App to EC2 via SSM (OIDC)

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::235494815059:role/github-actionOIDC
        aws-region: eu-north-1

    - name: Deploy via SSM to EC2
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy Node App via GitHub OIDC" \
          --instance-ids "i-04ac66feee251e0c0" \
          --parameters 'commands=[
            "APP_DIR=/home/ubuntu/myapp",
            "REPO_URL=https://github.com/12rutuja/nodejs-ssl-server.git",

            "# Clone or update the repo",
            "if [ ! -d \"$APP_DIR\" ]; then \
              git clone $REPO_URL $APP_DIR && cd $APP_DIR && npm install; \
            else \
              cd $APP_DIR && git reset --hard origin/main && git pull origin main && npm install; \
            fi",

            "# Ensure we are in app directory",
            "cd $APP_DIR",

            "# Ensure Node.js and PM2 are present",
            "which node && node -v",
            "which pm2 || sudo npm install -g pm2",

            "# Stop the previous app if running",
            "pm2 delete hello-node || echo 'App not running yet'",

            "# Start the app with PM2",
            "pm2 start server.js --name hello-node",

            "# Save PM2 state",
            "pm2 save",

            "# Optional: Enable PM2 startup on reboot",
            "pm2 startup systemd -u ubuntu --hp /home/ubuntu",

            "# Debugging: show PM2 list and logs",
            "pm2 list",
            "pm2 logs hello-node --lines 20",

            "# Confirm working directory",
            "echo App is running from $(pwd)"
          ]' \
          --region eu-north-1 \
          --output text
