name: Deploy Node.js App to EC2 via SSM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1  # replace with your region

    - name: Deploy via SSM to EC2
      run: |
        # Replace with your EC2 instance ID
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy Node App via GitHub Actions" \
          --instance-ids "i-04ac66feee251e0c0" \
          --parameters 'commands=[
            "cd ~/myapp || git clone https://github.com/12rutuja/nodejs-ssl-server.git ~/myapp",
            "cd ~/myapp",
            "git pull origin main",
            "npm install",
            "pm2 startOrReload ecosystem.config.js || pm2 start server.js --name hello-node"
          ]' \
          --region eu-north-1 \
          --query "Command.CommandId" \
          --output text

